# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
       key_id: "RXS4P723NR",
       issuer_id: "7018aa3b-edaa-4bf0-bcbf-57a53f9e8a6a",
       key_content: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR1RBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJIa3dkd0lCQVFRZ3hYWUErdXRvbHNTL2U0K0QKQVdBWkcweml1bTdlN0pWVzFESTl5dzdGMTYrZ0NnWUlLb1pJemowREFRZWhSQU5DQUFSV1VaQU5jWHN1bkljbwpoQS9ldWMvUDdkcHY4cEdKc2pJRDhPWEdia1I2SjZCRm5SV051bjBsL0Q1ajdQVEtHcjRjNFowNkl3NmlkMXU5Ck5xc1hPWi9BCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=",
       is_key_content_base64: true
     )
    increment_build_number(xcodeproj: "TemplateProject.xcodeproj")
    get_certificates( # Create or get certificate, and install it
      output_path: "./builds" # Download certificate in the build folder (you don't need to create the folder)
    )
    get_provisioning_profile( # Create or get provisioning profile
      output_path: "./builds",  # Download provisioning profile in the build folder
      filename: "provisioning.mobileprovision" # Rename the local provisioning profile
    )
    update_project_provisioning( # Set the project provisioning profile (related in Xcode to the General > Signing Release section)
      xcodeproj: "TemplateProject.xcodeproj",
      target_filter: "TemplateProject.xcodeproj", # Name of your project
      profile: "./builds/provisioning.mobileprovision",
      build_configuration: "Release"
    )
    update_project_team( # Set the right team on your project
      teamid: CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    )
    build_app(
       workspace: "TemplateProject.xcworkspace",
       scheme: "TemplateProject",
       clean: true,
       export_method: "app-store",
       export_options: {
         provisioningProfiles: {
             CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier) => CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier) + " AppStore" # Value of this parameter is the name of the Provisioning Profile. By default, it will be "{bundleId} AppStore"
         }
       },
       build_path: "./builds",
       output_directory: "./builds"
    )
    upload_to_testflight
  end
end
